-- schema/wbr_reports.sql
-- Materialized Weekly Business Review reports (Ch 20.5)
-- Generated by pg_cron every Monday at 6 AM UTC.
---
CREATE TABLE IF NOT EXISTS wbr_reports (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  week_start      date NOT NULL,
  report_json     jsonb NOT NULL,              -- Full WBR exception report
  exceptions      jsonb,                       -- Flagged exceptions only
  generated_at    timestamptz DEFAULT now(),
  UNIQUE(week_start)
);

CREATE INDEX IF NOT EXISTS idx_wbr_reports_week
  ON wbr_reports(week_start);

COMMENT ON TABLE wbr_reports IS
  'Materialized Weekly Business Review reports. '
  'Grain: one row per week. '
  'Generated by pg_cron Monday 06:00 UTC (Ch 20.5).';

-- pg_cron schedule (requires pg_cron extension active):
-- SELECT cron.schedule(
--   'wbr-weekly',
--   '0 6 * * 1',
--   $$INSERT INTO wbr_reports (week_start, report_json, generated_at)
--     SELECT date_trunc('week', CURRENT_DATE - INTERVAL '7 days')::date,
--            jsonb_agg(row_to_json(sub.*)), NOW()
--     FROM (...WBR query...) sub
--     ON CONFLICT (week_start) DO UPDATE
--       SET report_json = EXCLUDED.report_json, generated_at = EXCLUDED.generated_at$$
-- );
